{% set version = "1.2.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-catdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/catdata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/catdata/catdata_{{ version }}.tar.gz
  sha256: 1c586c2cc9dd1ec3d12d8d2fdbed1055bb36268449e82949efbac9eca45d71bf

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('catdata')"           # [not win]
    - "\"%R%\" -e \"library('catdata')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=catdata
  license: GPL-2.0-only
  summary: This R-package contains examples from the book "Regression for Categorical Data", Tutz 2012, Cambridge University Press. The names of the examples refer to the chapter and the data set that is used.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: catdata
# Type: Package
# Title: Categorical Data
# Version: 1.2.2
# Date: 2020-02-05
# Encoding: UTF-8
# Depends: MASS
# Suggests: rms, qvcalc, glmmML, nnet, pscl, VGAM, gee, mlogit, Ecdat, geepack, mgcv, rpart, party, ordinal, lme4, vcdExtra, glmnet, mboost, class, e1071, flexmix, lpSolve, GAMBoost, penalized
# Author: Gunther Schauberger, Gerhard Tutz
# Maintainer: Gunther Schauberger <gunther.schauberger@tum.de>
# Description: This R-package contains examples from the book "Regression for Categorical Data", Tutz 2012, Cambridge University Press. The names of the examples refer to the chapter and the data set that is used.
# License: GPL-2
# LazyLoad: yes
# NeedsCompilation: no
# Packaged: 2020-02-05 15:02:27 UTC; ge29weh
# Repository: CRAN
# Date/Publication: 2020-02-07 12:20:08 UTC
